export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const FETCH_PRODUCTS_SUCCES = 'FETCH_PRODUCTS_SUCCESS';

export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_START = 'FETCH_SEARCH_START';
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL';
export const FETCH_SEARCH_SUCCES = 'FETCH_SEARCH_SUCCESS';